services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: docker_postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - postgres_db

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=ses
      - DEBUG=localstack:ses
    volumes:
      - "./volume:/var/lib/localstack"  # Correct volume mount here
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./create-db.sql:/docker-entrypoint-initdb.d/create_db.sql"

volumes:
  db:  # Correctly define named volume

networks:
  postgres_db:
