services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: docker_postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - postgres_db

volumes:
  db:

networks:
  postgres_db: